const axios = require('axios');
const fs = require('fs');
const path = require('path');
const { FOOTBALL_API_KEY, API_BASE_URL, IS_DEMO_MODE } = require('../utils/config');

// Path to the Active Leagues Cache (Generated by sync script)
const ACTIVE_LEAGUES_FILE = path.resolve(__dirname, '../data/active_leagues.json');

// Simple In-Memory Cache
const apiCache = {};
const CACHE_TTL = {
    fixtures: 6 * 60 * 60 * 1000,  // 6 Hours: Schedules don't change often
    static: 24 * 60 * 60 * 1000    // 24 Hours for countries/leagues
};

function getCache(key) {
    const entry = apiCache[key];
    if (!entry) return null;
    if (Date.now() > entry.expiry) {
        delete apiCache[key];
        return null;
    }
    return entry.data;
}

function setCache(key, data, type = 'fixtures') {
    apiCache[key] = {
        data,
        expiry: Date.now() + CACHE_TTL[type]
    };
}

class FootballApi {
    constructor() {
        this.headers = {
            'x-apisports-key': FOOTBALL_API_KEY,
            'x-apisports-host': 'v3.football.api-sports.io'
        };
    }

    async getFixturesByTeam(teamId, next = 10, leagueId = null) {
        if (IS_DEMO_MODE) return this.getMockFixtures();
        
        // Cache key includes league filtering if present
        const cacheKey = `fixtures_${teamId}_${next}${leagueId ? `_${leagueId}` : ''}`;
        const cached = getCache(cacheKey);
        if (cached) {
            console.log('Serving from Cache:', cacheKey);
            return cached;
        }

        try {
            let params;
            
            if (leagueId) {
                // API-Sports doesn't support team+league+next together
                // Use season-based query and filter for future games
                const { getSeasonYear } = require('../utils/config');
                const season = getSeasonYear('academic'); // Use academic for most domestic cups
                
                params = { team: teamId, league: leagueId, season };
                console.log(`[Fixtures] Fetching team ${teamId} in league ${leagueId} for season ${season}`);
            } else {
                // Standard next N fixtures across all competitions
                params = { team: teamId, next };
            }

            const response = await axios.get(`${API_BASE_URL}/fixtures`, {
                params: params,
                headers: this.headers
            });
            
            let data = response.data.response;
            
            // If league filter was used, filter for future/upcoming games only
            if (leagueId && data.length > 0) {
                const now = new Date();
                data = data
                    .filter(f => new Date(f.fixture.date) >= now || f.fixture.status.short === 'NS')
                    .slice(0, next); // Limit to requested count
                console.log(`[Fixtures] Filtered to ${data.length} upcoming fixtures`);
            }
            
            setCache(cacheKey, data, 'fixtures');
            return data;
        } catch (error) {
            console.error('API Error:', error.message);
            return this.getMockFixtures();
        }
    }

    async getCountries() {
        if (IS_DEMO_MODE) return [{"name": "Israel", "code": "IL", "flag": "https://media.api-sports.io/flags/il.svg"}, {"name": "England", "code": "GB", "flag": "https://media.api-sports.io/flags/gb.svg"}];
        
        const cacheKey = 'countries_list';
        const cached = getCache(cacheKey);
        if (cached) return cached;

        try {
            const response = await axios.get(`${API_BASE_URL}/countries`, {
                headers: this.headers
            });
            const data = response.data.response;
            setCache(cacheKey, data, 'static');
            return data;
        } catch (error) {
            console.error('API Error (Countries):', error.message);
            return [];
        }
    }

    async getLeagues(country) {
        if (IS_DEMO_MODE) return [{"league":{"id":1,"name":"Ligat HaAl","type":"League","logo":"https://media.api-sports.io/football/leagues/1.png"},"country":{"name":"Israel","code":"IL","flag":"https://media.api-sports.io/flags/il.svg"},"seasons":[{"year":2023,"start":"2023-08-26","end":"2024-05-25","current":true}]}];
        
        // --- 1. Try Local Verified Cache First ---
        try {
            if (fs.existsSync(ACTIVE_LEAGUES_FILE)) {
                const raw = fs.readFileSync(ACTIVE_LEAGUES_FILE, 'utf-8');
                const allActive = JSON.parse(raw);
                
                // Filter for requested country & ensure active or vacation status
                // Also ignore "Archived" implicitly by checking against [active, vacation]
                const fromCache = allActive.filter(l => 
                    l.country.name === country && 
                    (l.verify_status === 'active' || l.verify_status === 'vacation')
                );

                if (fromCache.length > 0) {
                    // Transformation: Minimalist & Clean
                    const lightweight = fromCache.map(l => ({
                        id: l.league.id,
                        name: l.league.name,
                        type: l.league.type, // Kept for frontend routing
                        logo: l.league.logo,
                        status: l.verify_status,
                        ui_label: l.verify_status === 'active' ? "⚽ Active" : "🏖️ Vacation"
                    }));

                    // Logic: Sort by Status (Active First) -> Pinned ID 383 -> Name
                    lightweight.sort((a, b) => {
                        // 1. Status Priority: Active before Vacation
                        if (a.status !== b.status) {
                            return a.status === 'active' ? -1 : 1;
                        }
                        
                        // 2. Pin Specific ID (383 = Ligat Ha'al) to top of Active list
                        if (a.id === 383) return -1;
                        if (b.id === 383) return 1;

                        // 3. Alphabetical
                        return a.name.localeCompare(b.name);
                    });

                    console.log(`[API] Served ${lightweight.length} optimized leagues from cache (${country}).`);
                    return lightweight;
                }
            }
        } catch (e) {
            console.warn('[API] Failed to read active leagues cache, falling back to live API.', e.message);
        }
        
        // --- 2. Fallback to Standard API ---
        const cacheKey = `leagues_${country}`;
        const cached = getCache(cacheKey);
        if (cached) return cached;

        try {
            const response = await axios.get(`${API_BASE_URL}/leagues`, {
                params: { country: country, current: 'true' }, // Force current only for fallback
                headers: this.headers
            });
            console.log(`Fetched leagues for ${country}: ${response.data.response.length}`);
            
            const rawData = response.data.response;
            
            // Map to Lightweight format for consistency
            const lightweight = rawData.map(item => ({
                id: item.league.id,
                name: item.league.name,
                type: item.league.type,
                logo: item.league.logo,
                status: 'active', // Assume active for live fallback
                ui_label: "⚽ Active"
            }));
            
            setCache(cacheKey, lightweight, 'static');
            return lightweight;
        } catch (error) {
            console.error('API Error (Leagues):', error.message);
            return [];
        }
    }

    async getTeams(league, season) {
        if (IS_DEMO_MODE) return [{"team":{"id":1462,"name":"Maccabi Haifa","code":"MAC","country":"Israel","founded":1913,"national":false,"logo":"https://media.api-sports.io/football/teams/1462.png"},"venue":{"id":1111,"name":"Sammy Ofer Stadium","address":"Matam Park","city":"Haifa","capacity":30870,"surface":"grass","image":"https://media.api-sports.io/football/venues/1111.png"}}];
        
        const cacheKey = `teams_${league}_${season}`;
        const cached = getCache(cacheKey);
        if (cached) return cached;

        try {
            const response = await axios.get(`${API_BASE_URL}/teams`, {
                params: { league: league, season: season },
                headers: this.headers
            });
            const data = response.data.response;
            setCache(cacheKey, data, 'static');
            return data;
        } catch (error) {
            console.error('API Error (Teams):', error.message);
            return [];
        }
    }

    async getStandings(league, season) {
        if (IS_DEMO_MODE) return [];
        
        const cacheKey = `standings_${league}_${season}`;
        const cached = getCache(cacheKey, 'fixtures'); // Use 6h cache (standings update with games)
        if (cached) return cached;

        try {
            console.log(`[API] Fetching Standings: League ${league}, Season ${season}`);
            const response = await axios.get(`${API_BASE_URL}/standings`, {
                params: { league: league, season: season },
                headers: this.headers
            });
            
            const data = response.data.response;
            // Standings can be empty if season not started
            setCache(cacheKey, data, 'fixtures');
            return data;
        } catch (error) {
            console.error('API Error (Standings):', error.message);
            return []; // Return empty, caller handles fallback
        }
    }

    async getNationalTeam(country) {
        if (IS_DEMO_MODE) return [{"team": {id: 767, name: "Israel", national: true, logo: "https://media.api-sports.io/football/teams/767.png"}}];
        try {
            console.log(`Fetching National Team for: ${country}`);
            
            // Fix: API-Sports search fails when combining country + search for same string
            // Strategy: Search globally for the country name, then filter by country + national flag
            const response = await axios.get(`${API_BASE_URL}/teams`, {
                params: { search: country }, 
                headers: this.headers
            });
            
            const results = response.data.response;
            
            // Filter strictly:
            // 1. Must be a National Team
            // 2. Must belong to the requested Country
            // 3. Exclude "U21", "U19", "Women" to get the main Senior Team (optional, but usually desired as default)
            const nationalTeams = results.filter(t => 
                t.team.national === true && 
                t.team.country === country &&
                !t.team.name.includes('U21') &&
                !t.team.name.includes('U19') &&
                !t.team.name.includes('U17') &&
                !t.team.name.includes('Women')
            );

            if (nationalTeams.length > 0) {
                 console.log(`Found ${nationalTeams.length} national teams. Returning top match.`);
                 return nationalTeams;
            }

            console.log(`Structure check: Found ${results.length} total via search, but 0 matches after filter.`);
            return [];

        } catch (error) {
            console.error('API Error (National Team):', error.message);
            return [];
        }
    }

    async getFixturesByLeague(league, season, next = null, last = null, status = null) {
        // Cache key
        const cacheKey = `fixtures_lg_${league}_${season}_n${next}_l${last}_s${status}`;
        const cached = getCache(cacheKey);
        if (cached) return cached;

        try {
            const params = { league: league, season: season };
            
            // Priority: Status (All matching) > Last > Next
            if (status) {
                params.status = status;
            } else if (last) {
                params.last = last;
            } else {
                params.next = next || 10; // Default if nothing provided
            }

            console.log(`[API] Fetching League Fixtures:`, params);
            const response = await axios.get(`${API_BASE_URL}/fixtures`, {
                params: params,
                headers: this.headers
            });
            const data = response.data.response;
            setCache(cacheKey, data, 'fixtures');
            return data;
        } catch (error) {
            console.error('API Error (League Fixtures):', error.message);
            return [];
        }
    }

    /**
     * Universal Active Teams Funnel (Refactored)
     * Finds participating teams for a league/cup via:
     * 1. Upcoming Fixtures (Primary)
     * 2. Standings Table (Fallback for breaks/international windows)
     * 3. Recent Fixtures (Safety Net)
     * 4. Full Team List (Ultimate Fallback)
     * @param {number} leagueId 
     * @param {number} season 
     * @returns {Promise<Array>} List of clean ActiveTeam objects
     */
    async getActiveTournamentTeams(leagueId, season) {
        const cacheKey = `active_teams_${leagueId}_${season}`;
        
        const cached = getCache(cacheKey, 'fixtures');
        if (cached) {
            console.log(`[Funnel] Serving Cached Active Teams for ${leagueId}`);
            return cached;
        }

        console.log(`[Funnel] Starting Active Teams Search for League ${leagueId}/${season}`);
        const uniqueTeams = new Map();

        // Helper: Add team to unique map
        const addTeam = (t) => {
            if (t && t.id && !uniqueTeams.has(t.id)) {
                uniqueTeams.set(t.id, { id: t.id, name: t.name, logo: t.logo });
            }
        };

        // Helper: Enrich basic team IDs with full details (Venue, City, Code)
        const enrichTeams = async () => {
            if (uniqueTeams.size === 0) return [];
            
            try {
                const activeIds = new Set(uniqueTeams.keys());
                const allTeamsRich = await this.getTeams(leagueId, season);
                
                const enriched = allTeamsRich
                    .filter(item => item.team && activeIds.has(item.team.id))
                    .map(item => ({
                        id: item.team.id,
                        name: item.team.name,
                        logo: item.team.logo,
                        code: item.team.code,
                        founded: item.team.founded,
                        national: item.team.national,
                        venue: item.venue || {}
                    }));
                
                return enriched.length > 0 ? enriched : Array.from(uniqueTeams.values());
            } catch (err) {
                console.warn("[Funnel] Enrichment Error:", err.message);
                return Array.from(uniqueTeams.values());
            }
        };

        // --- Phase 1: Upcoming Fixtures (Primary Check) ---
        try {
            console.log("[Funnel] Phase 1: Checking Future Fixtures (status=NS)...");
            const futureFixtures = await this.getFixturesByLeague(leagueId, season, null, null, 'NS');
            
            if (futureFixtures && futureFixtures.length > 0) {
                futureFixtures.forEach(f => {
                    if (f.teams) {
                        addTeam(f.teams.home);
                        addTeam(f.teams.away);
                    }
                });
                console.log(`[Funnel] Phase 1 Success: Found ${uniqueTeams.size} teams from future games.`);
                
                const result = await enrichTeams();
                setCache(cacheKey, result, 'fixtures');
                return result;
            }
        } catch (err) {
            console.warn("[Funnel] Phase 1 Error:", err.message);
        }

        // --- Phase 2: Standings Fallback (For Leagues in Break / International Windows) ---
        try {
            console.log("[Funnel] Phase 1 Empty. Phase 2: Checking Standings...");
            const standingsData = await this.getStandings(leagueId, season);
            
            let flatList = [];
            if (standingsData && standingsData.length > 0 && standingsData[0].league && standingsData[0].league.standings) {
                // Standings can be: [[Group A], [Group B]] or just [Team1, Team2...]
                flatList = standingsData[0].league.standings.flat();
            }

            if (flatList.length > 0) {
                // Include all teams from standings (don't filter eliminated during breaks)
                flatList.forEach(s => addTeam(s.team));
                console.log(`[Funnel] Phase 2 Success: Found ${uniqueTeams.size} teams from Standings.`);
                
                const result = await enrichTeams();
                setCache(cacheKey, result, 'fixtures');
                return result;
            }
        } catch (err) {
            console.warn("[Funnel] Phase 2 Error:", err.message);
        }

        // --- Phase 3: Recent History (Safety Net) ---
        try {
            console.log("[Funnel] Phase 2 Empty. Phase 3: Checking Recent Fixtures (Last 20)...");
            const recentFixtures = await this.getFixturesByLeague(leagueId, season, null, 20, null);
            
            if (recentFixtures && recentFixtures.length > 0) {
                recentFixtures.forEach(f => {
                    if (f.teams) {
                        addTeam(f.teams.home);
                        addTeam(f.teams.away);
                    }
                });
                console.log(`[Funnel] Phase 3 Success: Found ${uniqueTeams.size} teams from recent history.`);
                
                const result = await enrichTeams();
                setCache(cacheKey, result, 'fixtures');
                return result;
            }
        } catch (err) {
            console.warn("[Funnel] Phase 3 Error:", err.message);
        }

        // --- Phase 4: Full Team List (Ultimate Fallback) ---
        try {
            console.log("[Funnel] Phase 3 Empty. Phase 4: Fetching Full Team List...");
            const allTeams = await this.getTeams(leagueId, season);
            
            if (allTeams && allTeams.length > 0) {
                const result = allTeams.map(item => ({
                    id: item.team.id,
                    name: item.team.name,
                    logo: item.team.logo,
                    code: item.team.code,
                    founded: item.team.founded,
                    national: item.team.national,
                    venue: item.venue || {}
                }));
                console.log(`[Funnel] Phase 4 Success: Found ${result.length} teams from Full List.`);
                setCache(cacheKey, result, 'static');
                return result;
            }
        } catch (err) {
            console.warn("[Funnel] Phase 4 Error:", err.message);
        }

        console.log("[Funnel] All Phases Failed. Returning 0 teams.");
        return [];
    }


    async getFixtureById(id) {
        // Implementation for single fixture
         try {
            const response = await axios.get(`${API_BASE_URL}/fixtures`, {
                params: { id: id },
                headers: this.headers
            });
            return response.data.response[0]; // Return single object
        } catch (error) {
            return null;
        }
    }
    
    async getFixturesByDate(date) {
         try {
            const response = await axios.get(`${API_BASE_URL}/fixtures`, {
                params: { date: date },
                headers: this.headers
            });
            return response.data.response;
        } catch (error) {
            return [];
        }
    }
    
    async getPastFixtures(teamId, last = 10) {
         try {
            const response = await axios.get(`${API_BASE_URL}/fixtures`, {
                params: { team: teamId, last: last, status: 'FT-AET-PEN' },
                headers: this.headers
            });
            return response.data.response;
        } catch (error) {
            return [];
        }
    }

    /**
     * Get the current season year for a specific league
     * Some leagues like UEFA Nations League, World Cup Qualifiers have non-standard year cycles
     */
    async getCurrentSeasonForLeague(leagueId) {
        const cacheKey = `current_season_${leagueId}`;
        const cached = getCache(cacheKey, 'static');
        if (cached) return cached;

        try {
            const response = await axios.get(`${API_BASE_URL}/leagues`, {
                params: { id: leagueId },
                headers: this.headers
            });
            
            const leagues = response.data.response;
            if (leagues && leagues.length > 0) {
                const seasons = leagues[0].seasons || [];
                const current = seasons.find(s => s.current);
                if (current) {
                    console.log(`[API] League ${leagueId} current season: ${current.year}`);
                    setCache(cacheKey, current.year, 'static');
                    return current.year;
                }
                // Fallback to latest season
                if (seasons.length > 0) {
                    const latest = seasons[seasons.length - 1].year;
                    setCache(cacheKey, latest, 'static');
                    return latest;
                }
            }
        } catch (error) {
            console.error(`[API] Error fetching current season for league ${leagueId}:`, error.message);
        }
        return null;
    }

    getMockFixtures() {
        return [{ fixture: { id: 1, date: new Date().toISOString() }, teams: { home: { name: 'Demo FC' }, away: { name: 'Mock City' } } }];
    }
}

module.exports = new FootballApi();
